#include "quark/CodeGen.h"
#include "quark/Error.h"

namespace {
    // Quark names live in their own namespace in the generated C, so a Quark
    // variable called `int` or `printf` cannot collide with anything.
    std::string mangle(const std::string& name) {
        return "q_" + name;
    }
}

std::string CodeGen::generate(Program* program) {
    out.str("");
    out.clear();

    out << "// Generated by quarkc. Do not edit.\n";
    out << "#include <stdio.h>\n";
    out << "\n";
    out << "int main(void) {\n";

    for (Stmt* stmt : program->statements) {
        emitStatement(stmt);
    }

    out << "    return 0;\n";
    out << "}\n";

    return out.str();
}

void CodeGen::emitStatement(Stmt* stmt) {
    if (LetStmt* let = dynamic_cast<LetStmt*>(stmt)) {
        out << "    int " << mangle(let->name) << " = " << emitExpression(let->value) << ";\n";
        return;
    }

    if (AssignStmt* assign = dynamic_cast<AssignStmt*>(stmt)) {
        out << "    " << mangle(assign->name) << " = " << emitExpression(assign->value) << ";\n";
        return;
    }

    if (ExprStmt* expression = dynamic_cast<ExprStmt*>(stmt)) {
        out << "    " << emitExpression(expression->expr) << ";\n";
        return;
    }

    throw CompileError(stmt->line, "Cannot generate code for this statement");
}

std::string CodeGen::emitExpression(Expr* expr) {
    if (IntegerExpr* integer = dynamic_cast<IntegerExpr*>(expr)) {
        return std::to_string(integer->value);
    }

    if (IdentifierExpr* identifier = dynamic_cast<IdentifierExpr*>(expr)) {
        return mangle(identifier->name);
    }

    if (UnaryExpr* unary = dynamic_cast<UnaryExpr*>(expr)) {
        return "(" + unary->op + emitExpression(unary->operand) + ")";
    }

    if (BinaryExpr* binary = dynamic_cast<BinaryExpr*>(expr)) {
        // Parenthesise everything: the AST already encodes precedence, so the
        // generated C must not be re-associated by C's own rules.
        return "(" + emitExpression(binary->left) +
               " " + binary->op + " " +
               emitExpression(binary->right) + ")";
    }

    if (CallExpr* call = dynamic_cast<CallExpr*>(expr)) {
        // The analyzer has already guaranteed this is print/1.
        if (call->callee == "print") {
            return "printf(\"%d\\n\", " + emitExpression(call->args[0]) + ")";
        }

        throw CompileError(call->line, "Unknown function: " + call->callee);
    }

    throw CompileError(expr->line, "Cannot generate code for this expression");
}
